/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './product-detail.component.scss.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '../../../../src/app/product-detail/product-detail.component';
const styles_ProductDetailComponent:any[] = [i0.styles];
export const RenderType_ProductDetailComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_ProductDetailComponent,data:{}});
export function View_ProductDetailComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted((null as any),['Product detail component']))],(null as any),(null as any));
}
export function View_ProductDetailComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'product-detail',
      ([] as any[]),(null as any),(null as any),(null as any),View_ProductDetailComponent_0,
      RenderType_ProductDetailComponent)),i1.ɵdid(114688,(null as any),0,i2.ProductDetailComponent,
      ([] as any[]),(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const ProductDetailComponentNgFactory:i1.ComponentFactory<i2.ProductDetailComponent> = i1.ɵccf('product-detail',
    i2.ProductDetailComponent,View_ProductDetailComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovaW50ZXJuZXQtc2hvcC9zcmMvYXBwL3Byb2R1Y3QtZGV0YWlsL3Byb2R1Y3QtZGV0YWlsLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9EOi9pbnRlcm5ldC1zaG9wL3NyYy9hcHAvcHJvZHVjdC1kZXRhaWwvcHJvZHVjdC1kZXRhaWwuY29tcG9uZW50LnRzIiwibmc6Ly8vRDovaW50ZXJuZXQtc2hvcC9zcmMvYXBwL3Byb2R1Y3QtZGV0YWlsL3Byb2R1Y3QtZGV0YWlsLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRDovaW50ZXJuZXQtc2hvcC9zcmMvYXBwL3Byb2R1Y3QtZGV0YWlsL3Byb2R1Y3QtZGV0YWlsLmNvbXBvbmVudC50cy5Qcm9kdWN0RGV0YWlsQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGgxPlByb2R1Y3QgZGV0YWlsIGNvbXBvbmVudDwvaDE+IiwiPHByb2R1Y3QtZGV0YWlsPjwvcHJvZHVjdC1kZXRhaWw+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUEsd0VBQUk7YUFBQTs7O29CQ0FKO01BQUE7dUNBQUEsVUFBQTtNQUFBO0lBQUE7Ozs7In0=
