/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './home.component.scss.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '../../../../src/app/home/home.component';
const styles_HomeComponent:any[] = [i0.styles];
export const RenderType_HomeComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_HomeComponent,data:{}});
export function View_HomeComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted((null as any),['Home component']))],(null as any),(null as any));
}
export function View_HomeComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-home',([] as any[]),
      (null as any),(null as any),(null as any),View_HomeComponent_0,RenderType_HomeComponent)),
      i1.ɵdid(114688,(null as any),0,i2.HomeComponent,([] as any[]),(null as any),
          (null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const HomeComponentNgFactory:i1.ComponentFactory<i2.HomeComponent> = i1.ɵccf('app-home',
    i2.HomeComponent,View_HomeComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovaW50ZXJuZXQtc2hvcC9zcmMvYXBwL2hvbWUvaG9tZS5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRDovaW50ZXJuZXQtc2hvcC9zcmMvYXBwL2hvbWUvaG9tZS5jb21wb25lbnQudHMiLCJuZzovLy9EOi9pbnRlcm5ldC1zaG9wL3NyYy9hcHAvaG9tZS9ob21lLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRDovaW50ZXJuZXQtc2hvcC9zcmMvYXBwL2hvbWUvaG9tZS5jb21wb25lbnQudHMuSG9tZUNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxoMT5Ib21lIGNvbXBvbmVudDwvaDE+IiwiPGFwcC1ob21lPjwvYXBwLWhvbWU+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUEsd0VBQUk7YUFBQTs7O29CQ0FKO01BQUE7YUFBQTtVQUFBO0lBQUE7Ozs7In0=
