/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './app.component.scss.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './header/header.component.ngfactory';
import * as i3 from '../../../src/app/header/header.component';
import * as i4 from '@angular/router';
import * as i5 from '@angular/common';
import * as i6 from './footer/footer.component.ngfactory';
import * as i7 from '../../../src/app/footer/footer.component';
import * as i8 from '../../../src/app/app.component';
const styles_AppComponent:any[] = [i0.styles];
export const RenderType_AppComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,styles:styles_AppComponent,
    data:{}});
export function View_AppComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-header',([] as any[]),
      (null as any),(null as any),(null as any),i2.View_HeaderComponent_0,i2.RenderType_HeaderComponent)),
      i1.ɵdid(114688,(null as any),0,i3.HeaderComponent,([] as any[]),(null as any),
          (null as any)),(_l()(),i1.ɵted((null as any),['\n'])),(_l()(),i1.ɵeld(0,
          (null as any),(null as any),9,'nav',([] as any[]),(null as any),(null as any),
          (null as any),(null as any),(null as any))),(_l()(),i1.ɵted((null as any),
          ['\n    '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),2,'a',[['routerLink',
          '/home']],[[1,'target',0],[8,'href',4]],[[(null as any),'click']],(_v,en,
          $event) => {
        var ad:boolean = true;
        if (('click' === en)) {
          const pd_0:any = ((<any>i1.ɵnov(_v,6).onClick($event.button,$event.ctrlKey,
              $event.metaKey,$event.shiftKey)) !== false);
          ad = (pd_0 && ad);
        }
        return ad;
      },(null as any),(null as any))),i1.ɵdid(671744,(null as any),0,i4.RouterLinkWithHref,
          [i4.Router,i4.ActivatedRoute,i5.LocationStrategy],{routerLink:[0,'routerLink']},
          (null as any)),(_l()(),i1.ɵted((null as any),['Home'])),(_l()(),i1.ɵted((null as any),
          ['\n    '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),2,'a',[['routerLink',
          '/products']],[[1,'target',0],[8,'href',4]],[[(null as any),'click']],(_v,
          en,$event) => {
        var ad:boolean = true;
        if (('click' === en)) {
          const pd_0:any = ((<any>i1.ɵnov(_v,10).onClick($event.button,$event.ctrlKey,
              $event.metaKey,$event.shiftKey)) !== false);
          ad = (pd_0 && ad);
        }
        return ad;
      },(null as any),(null as any))),i1.ɵdid(671744,(null as any),0,i4.RouterLinkWithHref,
          [i4.Router,i4.ActivatedRoute,i5.LocationStrategy],{routerLink:[0,'routerLink']},
          (null as any)),(_l()(),i1.ɵted((null as any),['Products'])),(_l()(),i1.ɵted((null as any),
          ['\n'])),(_l()(),i1.ɵted((null as any),['\n'])),(_l()(),i1.ɵeld(16777216,
          (null as any),(null as any),1,'router-outlet',([] as any[]),(null as any),
          (null as any),(null as any),(null as any),(null as any))),i1.ɵdid(212992,
          (null as any),0,i4.RouterOutlet,[i4.ChildrenOutletContexts,i1.ViewContainerRef,
              i1.ComponentFactoryResolver,[8,(null as any)],i1.ChangeDetectorRef],
          (null as any),(null as any)),(_l()(),i1.ɵted((null as any),['\n'])),(_l()(),
          i1.ɵeld(0,(null as any),(null as any),1,'app-footer',([] as any[]),(null as any),
              (null as any),(null as any),i6.View_FooterComponent_0,i6.RenderType_FooterComponent)),
      i1.ɵdid(114688,(null as any),0,i7.FooterComponent,([] as any[]),(null as any),
          (null as any))],(_ck,_v) => {
    _ck(_v,1,0);
    const currVal_2:any = '/home';
    _ck(_v,6,0,currVal_2);
    const currVal_5:any = '/products';
    _ck(_v,10,0,currVal_5);
    _ck(_v,15,0);
    _ck(_v,18,0);
  },(_ck,_v) => {
    const currVal_0:any = i1.ɵnov(_v,6).target;
    const currVal_1:any = i1.ɵnov(_v,6).href;
    _ck(_v,5,0,currVal_0,currVal_1);
    const currVal_3:any = i1.ɵnov(_v,10).target;
    const currVal_4:any = i1.ɵnov(_v,10).href;
    _ck(_v,9,0,currVal_3,currVal_4);
  });
}
export function View_AppComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-root',([] as any[]),
      (null as any),(null as any),(null as any),View_AppComponent_0,RenderType_AppComponent)),
      i1.ɵdid(114688,(null as any),0,i8.AppComponent,([] as any[]),(null as any),(null as any))],
      (_ck,_v) => {
        _ck(_v,1,0);
      },(null as any));
}
export const AppComponentNgFactory:i1.ComponentFactory<i8.AppComponent> = i1.ɵccf('app-root',
    i8.AppComponent,View_AppComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovaW50ZXJuZXQtc2hvcC9zcmMvYXBwL2FwcC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRDovaW50ZXJuZXQtc2hvcC9zcmMvYXBwL2FwcC5jb21wb25lbnQudHMiLCJuZzovLy9EOi9pbnRlcm5ldC1zaG9wL3NyYy9hcHAvYXBwLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRDovaW50ZXJuZXQtc2hvcC9zcmMvYXBwL2FwcC5jb21wb25lbnQudHMuQXBwQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGFwcC1oZWFkZXI+PC9hcHAtaGVhZGVyPlxyXG48bmF2PlxyXG4gICAgPGEgcm91dGVyTGluaz1cIi9ob21lXCI+SG9tZTwvYT5cclxuICAgIDxhIHJvdXRlckxpbms9XCIvcHJvZHVjdHNcIj5Qcm9kdWN0czwvYT5cclxuPC9uYXY+XHJcbjxyb3V0ZXItb3V0bGV0Pjwvcm91dGVyLW91dGxldD5cclxuPGFwcC1mb290ZXI+PC9hcHAtZm9vdGVyPiIsIjxhcHAtcm9vdD48L2FwcC1yb290PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztvQkNBQTtNQUFBO2FBQUE7VUFBQSxlQUF5Qix1Q0FDekI7VUFBQTtVQUFBLDRDQUFLO1VBQUEsYUFDRDtVQUFBO2dCQUFBO1FBQUE7UUFBQTtVQUFBO2NBQUE7VUFBQTtRQUFBO1FBQUE7TUFBQSx1Q0FBQTtVQUFBO1VBQUEsZUFBc0IseUNBQVE7VUFBQSxhQUM5QjtVQUFBO21CQUFBO1FBQUE7UUFBQTtVQUFBO2NBQUE7VUFBQTtRQUFBO1FBQUE7TUFBQSx1Q0FBQTtVQUFBO1VBQUEsZUFBMEIsNkNBQVk7VUFBQSxTQUNwQyx1Q0FDTjtVQUFBO1VBQUEsaUVBQUE7VUFBQTswQ0FBQTtVQUFBLDZCQUErQix1Q0FDL0I7aUJBQUE7Y0FBQTthQUFBO1VBQUE7SUFOQTtJQUVPO0lBQUgsV0FBRyxTQUFIO0lBQ0c7SUFBSCxZQUFHLFNBQUg7SUFFSjtJQUNBOztJQUpJO0lBQUE7SUFBQSxXQUFBLG1CQUFBO0lBQ0E7SUFBQTtJQUFBLFdBQUEsbUJBQUE7Ozs7b0JDSEo7TUFBQTthQUFBOztRQUFBOzs7OyJ9
