/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './product-list.component.scss.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '@angular/router';
import * as i3 from '@angular/common';
import * as i4 from '../../../../src/app/product-list/product-list.component';
import * as i5 from '../../../../src/app/shared/product-service/product-service';
const styles_ProductListComponent:any[] = [i0.styles];
export const RenderType_ProductListComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_ProductListComponent,data:{}});
function View_ProductListComponent_1(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),11,'li',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted((null as any),['\n        '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),
      5,'a',([] as any[]),[[1,'target',0],[8,'href',4]],[[(null as any),'click']],
      (_v,en,$event) => {
        var ad:boolean = true;
        if (('click' === en)) {
          const pd_0:any = ((<any>i1.ɵnov(_v,3).onClick($event.button,$event.ctrlKey,
              $event.metaKey,$event.shiftKey)) !== false);
          ad = (pd_0 && ad);
        }
        return ad;
      },(null as any),(null as any))),i1.ɵdid(671744,(null as any),0,i2.RouterLinkWithHref,
      [i2.Router,i2.ActivatedRoute,i3.LocationStrategy],{routerLink:[0,'routerLink']},
      (null as any)),(_l()(),i1.ɵted((null as any),['\n            '])),(_l()(),i1.ɵeld(0,
      (null as any),(null as any),1,'span',[['class','badge']],(null as any),(null as any),
      (null as any),(null as any),(null as any))),(_l()(),i1.ɵted((null as any),['',
      ''])),(_l()(),i1.ɵted((null as any),[' ','\n        '])),(_l()(),i1.ɵted((null as any),
      ['\n        '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'button',[['class',
      'delete'],['title','delete product']],(null as any),[[(null as any),'click']],
      (_v,en,$event) => {
        var ad:boolean = true;
        var _co:any = _v.component;
        if (('click' === en)) {
          const pd_0:any = ((<any>_co.delete(_v.context.$implicit)) !== false);
          ad = (pd_0 && ad);
        }
        return ad;
      },(null as any),(null as any))),(_l()(),i1.ɵted((null as any),['x'])),(_l()(),
      i1.ɵted((null as any),['\n    ']))],(_ck,_v) => {
    const currVal_2:any = i1.ɵinlineInterpolate(1,'/product/',_v.context.$implicit.id,
        '');
    _ck(_v,3,0,currVal_2);
  },(_ck,_v) => {
    const currVal_0:any = i1.ɵnov(_v,3).target;
    const currVal_1:any = i1.ɵnov(_v,3).href;
    _ck(_v,2,0,currVal_0,currVal_1);
    const currVal_3:any = _v.context.$implicit.id;
    _ck(_v,6,0,currVal_3);
    const currVal_4:any = _v.context.$implicit.name;
    _ck(_v,7,0,currVal_4);
  });
}
export function View_ProductListComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted((null as any),['Product list component'])),(_l()(),i1.ɵted((null as any),
      ['\n\n'])),(_l()(),i1.ɵeld(0,(null as any),(null as any),4,'ul',[['class','products']],
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted((null as any),['\n    '])),(_l()(),i1.ɵand(16777216,(null as any),(null as any),
      1,(null as any),View_ProductListComponent_1)),i1.ɵdid(802816,(null as any),0,
      i3.NgForOf,[i1.ViewContainerRef,i1.TemplateRef,i1.IterableDiffers],{ngForOf:[0,
          'ngForOf']},(null as any)),(_l()(),i1.ɵted((null as any),['\n']))],(_ck,
      _v) => {
    var _co:i4.ProductListComponent = _v.component;
    const currVal_0:any = _co.products;
    _ck(_v,6,0,currVal_0);
  },(null as any));
}
export function View_ProductListComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'product-list',
      ([] as any[]),(null as any),(null as any),(null as any),View_ProductListComponent_0,
      RenderType_ProductListComponent)),i1.ɵdid(114688,(null as any),0,i4.ProductListComponent,
      [i5.ProductService],(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const ProductListComponentNgFactory:i1.ComponentFactory<i4.ProductListComponent> = i1.ɵccf('product-list',
    i4.ProductListComponent,View_ProductListComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovaW50ZXJuZXQtc2hvcC9zcmMvYXBwL3Byb2R1Y3QtbGlzdC9wcm9kdWN0LWxpc3QuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Q6L2ludGVybmV0LXNob3Avc3JjL2FwcC9wcm9kdWN0LWxpc3QvcHJvZHVjdC1saXN0LmNvbXBvbmVudC50cyIsIm5nOi8vL0Q6L2ludGVybmV0LXNob3Avc3JjL2FwcC9wcm9kdWN0LWxpc3QvcHJvZHVjdC1saXN0LmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRDovaW50ZXJuZXQtc2hvcC9zcmMvYXBwL3Byb2R1Y3QtbGlzdC9wcm9kdWN0LWxpc3QuY29tcG9uZW50LnRzLlByb2R1Y3RMaXN0Q29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGgxPlByb2R1Y3QgbGlzdCBjb21wb25lbnQ8L2gxPlxyXG5cclxuPHVsIGNsYXNzPVwicHJvZHVjdHNcIj5cclxuICAgIDxsaSAqbmdGb3I9XCJsZXQgcHJvZHVjdCBvZiBwcm9kdWN0c1wiPlxyXG4gICAgICAgIDxhIHJvdXRlckxpbms9XCIvcHJvZHVjdC97e3Byb2R1Y3QuaWR9fVwiPlxyXG4gICAgICAgICAgICA8c3BhbiBjbGFzcz1cImJhZGdlXCI+e3twcm9kdWN0LmlkfX08L3NwYW4+IHt7cHJvZHVjdC5uYW1lfX1cclxuICAgICAgICA8L2E+XHJcbiAgICAgICAgPGJ1dHRvbiBjbGFzcz1cImRlbGV0ZVwiIHRpdGxlPVwiZGVsZXRlIHByb2R1Y3RcIlxyXG4gICAgICAgICAgICAgICAgKGNsaWNrKT1cImRlbGV0ZShwcm9kdWN0KVwiPng8L2J1dHRvbj5cclxuICAgIDwvbGk+XHJcbjwvdWw+IiwiPHByb2R1Y3QtbGlzdD48L3Byb2R1Y3QtbGlzdD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDR0k7TUFBQSx3RUFBcUM7YUFBQSxnQ0FDakM7TUFBQTtNQUFBO1FBQUE7UUFBQTtVQUFBO2NBQUE7VUFBQTtRQUFBO1FBQUE7TUFBQSx1Q0FBQTtNQUFBO01BQUEsZUFBd0MsbURBQ3BDO01BQUE7TUFBQSw0Q0FBb0I7TUFBQSxNQUFxQixtREFDekM7TUFBQSxpQkFDSjtNQUFBO01BQUE7UUFBQTtRQUFBO1FBQ1E7VUFBQTtVQUFBO1FBQUE7UUFEUjtNQUFBLGdDQUNrQyxzQ0FBVTthQUFBO0lBSnpDO1FBQUE7SUFBSCxXQUFHLFNBQUg7O0lBQUE7SUFBQTtJQUFBLFdBQUEsbUJBQUE7SUFDd0I7SUFBQTtJQUFxQjtJQUFBOzs7O29CQUxyRDtNQUFBLHdFQUFJO2FBQUEsNENBQTJCO01BQUEsV0FFL0I7TUFBQSx3RUFBcUI7YUFBQSw0QkFDakI7TUFBQSxxREFBQTtpQkFBQTtVQUFBLDJCQU1LOzs7SUFORDtJQUFKLFdBQUksU0FBSjs7OztvQkNISjtNQUFBO3FDQUFBLFVBQUE7TUFBQTtJQUFBOzs7OyJ9
